import { MusicControl } from "@/components/MusicControl";
import Navigation from "@/components/Navigation";
import VideoBackground from "@/components/VideoBackground";
import "@coinbase/onchainkit/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background dark">
        <MusicControl />
        <Providers>
          <VideoBackground videoSrc="/video/background.mp4" >
            <Navigation />
            {children}
          </VideoBackground>
        </Providers>

      </body>
    </html>
  );
}
